export const MIRROR_DIR_NAME = "tui-state"
export const MIRROR_SCHEMA_VERSION = 1
export const STALE_MS = 6_000
export const LOOP_FRESH_MS = 120_000
export const POLL_INTERVAL_MS = 1_000
export const HEARTBEAT_MS = 2_000
export const MIN_HEARTBEAT_MS = 250
export const MIRROR_KEEPALIVE_MS = STALE_MS / 2
export const IDLE_RECHECK_MS = 10_000
export const MAX_IDLE_RECHECK_MS = 600_000
export const HEARTBEAT_ENV = "OMO_TUI_MIRROR_HEARTBEAT_MS"
export const IDLE_RECHECK_ENV = "OMO_TUI_MIRROR_IDLE_RECHECK_MS"
export const WRITE_DEBOUNCE_MS = 250
export const MAX_AGENTS = 12
export const MAX_JOBS = 12
export const LABEL_MAX = 24
